version: '3.3'
services:
  db:
    container_name: mysaql-sample
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3314:3306"
    volumes:
      - "./docker/mysql/initdb.d:/docker-entrypoint-initdb.d"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/log:/var/log/mysql"
  nginx:
    container_name: nginx-sample
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/images:/nginx/images"
